name: deploy


on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/morgana_engine
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Configura o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Installs requirements
      run: |
        python -m pip install -r dev-requirements.txt
    - name: Runs tests
      run: |
        python -m pytest --cov=morgana_engine tests/
    - name: Static typing check
      run: |
        python -m mypy ./morgana_engine
    - name: Code quality check
      run: |
        python -m pylama --ignore E203 ./morgana_engine
    - name: Installs dependencies and builds the package
      if: startsWith(github.ref, 'refs/tags')
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
        python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1